# Generated by Django 4.2.7 on 2025-06-06 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_badge', models.CharField(max_length=50)),
                ('description_badge', models.TextField(blank=True)),
                ('date_obtention', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('description_habit', models.TextField(blank=True)),
                ('frequence', models.CharField(choices=[('quotidien', 'Quotidien'), ('hebdomadaire', 'Hebdomadaire')], max_length=25)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fait', models.BooleanField(default=False)),
                ('habitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit.habitude')),
            ],
        ),
    ]
