# Generated by Django 4.2.7 on 2025-06-17 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habit', '0002_badge_utilisateur_habitude_derniere_realisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image_url',
            field=models.CharField(blank=True, help_text="Chemin vers l'image du badge si applicable", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='type_visuel',
            field=models.CharField(blank=True, help_text="Type de représentation visuelle (ex: 'tree', 'star')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='habitude',
            name='suivi_par_defaut',
            field=models.BooleanField(default=False, help_text="Marquer comme 'fait' automatiquement si aucune action n'est prise pour la période."),
        ),
        migrations.AlterField(
            model_name='badge',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
