# Generated by Django 5.2.3 on 2025-06-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_badge_image_url_badge_type_visuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitude',
            name='frequence',
            field=models.CharField(choices=[('quotidien', 'Quotidien'), ('hebdomadaire', 'Hebdomadaire'), ('mensuelle', 'Mensuelle')], max_length=25),
        ),
    ]
